### ISSUE TITLE
Solved: No output from hermesNB block

### ISSUE THREAD

**Issue by mgarrett1955** [Tom-McDermott/gr-hpsdr#12]
Solved: see below.. 

I set up a simple flow graph with a constant source and a QT Frequency sink.

The flow graph is running, the verbose output is printing the information, but I see nothing on the spectrum.

The unit is an Anan 10E, the Hermes reported version is 12(dec) C(hex).

I do hear the input antenna relays change state when I change the antenna configuration.

I am set for a single receiver, at 48000.

I compiled and installed the source from the latest repository.

Is it possible that the Anan. Hermes I have uses revision 2 or a latter version of the protocol?

I am using Gnuradio 3.7 on Ubuntu 16, gnuradio installed from package.

Thank you in advance.

**Comment by mgarrett1955** [comment]
Well, I fixed it by changing the number of samples in the QT FFT setting!! Now it works at all settings, so it seems that it is a bug in my particular version of the QT Frequency widget!! ARG...

Thank you for the great work. I will continue to implement my GRC setup/

**Comment by Tom-McDermott** [comment]
This bug is present on many versions of gnuradio that I have seen - Linux
and Windows on
multiple 3.7 versions I've tried.  It appears to be a QT problem, and I
think has been reported off and on
at the gnuradio mailing list (but not addressed).

It's not related to gr-hpsdr, it happens with other radios and protocols as
well.

-- Tom, N5EG
